// PM2 prod : queue + planificateur + Reverb (WebSocket, 0.0.0.0:8080).
module.exports = {
    apps: [
        {
            name: 'portalfy-queue',
            cwd: __dirname,
            script: 'artisan',
            args: 'queue:work --tries=3 --timeout=60 --sleep=3',
            interpreter: 'php',
            instances: 1,
            exec_mode: 'fork',
            autorestart: true,
            watch: false,
            // Le worker garde en mémoire le code bootstrapé entre les jobs ; on le recycle
            // périodiquement pour éviter toute fuite mémoire longue durée.
            max_memory_restart: '300M',
            min_uptime: '30s',
            max_restarts: 10,
            restart_delay: 3000,
            // Laisse le job en cours se terminer proprement avant le SIGKILL.
            kill_timeout: 15000,
            time: true,
            merge_logs: true,
            out_file: 'storage/logs/pm2-queue.out.log',
            error_file: 'storage/logs/pm2-queue.error.log',
        },
        {
            name: 'portalfy-schedule',
            cwd: __dirname,
            script: 'artisan',
            args: 'schedule:work',
            interpreter: 'php',
            instances: 1,
            exec_mode: 'fork',
            autorestart: true,
            watch: false,
            min_uptime: '30s',
            max_restarts: 10,
            restart_delay: 3000,
            kill_timeout: 5000,
            time: true,
            merge_logs: true,
            out_file: 'storage/logs/pm2-schedule.out.log',
            error_file: 'storage/logs/pm2-schedule.error.log',
        },
        {
            name: 'portalfy-reverb',
            cwd: __dirname,
            script: 'artisan',
            args: 'reverb:start --host=0.0.0.0 --port=8080',
            interpreter: 'php',
            instances: 1,
            exec_mode: 'fork',
            autorestart: true,
            watch: false,
            min_uptime: '30s',
            max_restarts: 10,
            restart_delay: 3000,
            // Laisse les connexions WebSocket ouvertes se fermer proprement avant le SIGKILL.
            kill_timeout: 10000,
            time: true,
            merge_logs: true,
            out_file: 'storage/logs/pm2-reverb.out.log',
            error_file: 'storage/logs/pm2-reverb.error.log',
        },
    ],
};
